/*
  # AI Career Planner - Seed Data

  ## Overview
  Seeds the database with initial hardcoded jobs and crowdsourced statistics
  for demonstration purposes.

  ## 1. Jobs Data

  Inserts 10 curated job listings across different disciplines and sources:
  - Tech/STEM roles for university students
  - Internships for high school students
  - Business and general roles
  - Mix of legitimate jobs and high-risk scam examples

  ## 2. Crowdsourced Stats Data

  Inserts response statistics for 5 companies to demonstrate the
  crowdsourced data feature.

  ## 3. Important Notes

  - Uses INSERT ... ON CONFLICT DO NOTHING for idempotent seeding
  - Scam scores range from 0.1 (safe) to 0.9 (high risk)
  - Job IDs are auto-generated by bigserial
  - All jobs link to example URLs (not real job postings)
*/

-- Seed jobs data
INSERT INTO jobs (title, company, source, url, description, discipline, scam_score) VALUES
  (
    'Junior Data Scientist',
    'TechCorp HK',
    'JobsDB',
    'https://hk.jobsdb.com/job/junior-data-scientist',
    'Join our data science team to build machine learning models for customer analytics. Requirements: Python, SQL, basic ML knowledge. Fresh graduates welcome.',
    'Tech',
    0.1
  ),
  (
    'Software Engineering Intern',
    'StartupHub',
    'LinkedIn',
    'https://www.linkedin.com/jobs/software-engineering-intern',
    'Summer internship program for computer science students. Work on real-world projects with mentorship. Duration: 8-10 weeks.',
    'Internship',
    0.1
  ),
  (
    'Marketing Assistant',
    'BrandCo',
    'CTgoodjobs',
    'https://www.ctgoodjobs.hk/marketing-assistant',
    'Support marketing campaigns, social media management, and market research. Suitable for business or communications students.',
    'Business',
    0.15
  ),
  (
    'Retail Sales Associate',
    'MegaStore',
    'CTgoodjobs',
    'https://www.ctgoodjobs.hk/retail-sales',
    'Part-time retail position in Causeway Bay. Flexible hours, suitable for students. Customer service experience preferred.',
    'Internship',
    0.2
  ),
  (
    'Research Assistant',
    'HKU Department of Biology',
    'LinkedIn',
    'https://www.linkedin.com/jobs/research-assistant-biology',
    'Assist with laboratory research in marine biology. Requirements: BSc in Biology or related field. 1-year contract.',
    'Science',
    0.1
  ),
  (
    'Business Analyst Trainee',
    'ConsultPro',
    'JobsDB',
    'https://hk.jobsdb.com/job/business-analyst-trainee',
    'Graduate trainee program in business consulting. Training provided. Looking for analytical mindset and strong communication skills.',
    'Business',
    0.15
  ),
  (
    'Graphic Designer (Intern)',
    'Creative Studio',
    'Openjobs',
    'https://www.openjobs.hk/graphic-designer-intern',
    'Design internship for students studying visual arts, multimedia, or graphic design. Build portfolio with real client work.',
    'Arts',
    0.2
  ),
  (
    'Customer Service Representative',
    'CallCenter Plus',
    'Openjobs',
    'https://www.openjobs.hk/customer-service',
    'Handle customer inquiries via phone and email. Training provided. Shift work required. Bonus incentives available.',
    'General',
    0.3
  ),
  (
    'Easy Money Online Job - No Experience Required!',
    'QuickCash Ltd',
    'Openjobs',
    'https://www.openjobs.hk/easy-money-scam',
    'Earn $5000-$8000 per week working from home! No skills needed, just your smartphone. Pay upfront training fee of $500 to get started. Guaranteed income!',
    'General',
    0.9
  ),
  (
    'Investment Opportunity Coordinator',
    'FastProfit Group',
    'CTgoodjobs',
    'https://www.ctgoodjobs.hk/investment-coordinator',
    'Recruit investors for high-return investment schemes. Earn commission on every sign-up! Must be comfortable handling large cash transactions.',
    'Business',
    0.75
  )
ON CONFLICT DO NOTHING;

-- Seed crowdsourced stats data
INSERT INTO crowdsourced_stats (company, response_rate, avg_response_time) VALUES
  ('TechCorp HK', 80, '1 week'),
  ('StartupHub', 65, '3-5 days'),
  ('BrandCo', 70, '2 weeks'),
  ('HKU Department of Biology', 85, '1-2 weeks'),
  ('ConsultPro', 75, '10 days')
ON CONFLICT (company) DO NOTHING;
